// Plugin management configuration
pluginManagement {
    repositories {
        gradlePluginPortal()
        //uncomment to look for plugins in local maven (.m2) folder
        mavenLocal()
        google() // needed for Android Gradle Plugin
    }
}

// Common modules
include ':common:otel',
        ':common:storage',
        ':common:utils'

// Instrumentation modules
include ':instrumentation:runtime:startup',
        ':instrumentation:runtime:okhttp3-common',
        ':instrumentation:runtime:okhttp3-manual',
        ':instrumentation:runtime:okhttp3-auto',
        ':instrumentation:runtime:httpurlconnection-auto',
        ':instrumentation:runtime:slowrendering',
        ':instrumentation:buildtime:httpurlconnection-auto:agent',
        ':instrumentation:buildtime:httpurlconnection-auto:plugin',
        ':instrumentation:buildtime:okhttp3-auto:agent',
        ':instrumentation:buildtime:okhttp3-auto:plugin',
        ':instrumentation:buildtime:mapping-file:plugin'

// Integration
include ':integration:agent:api',
        ':integration:agent:common',
        ':integration:agent:internal',
        ':integration:startup',
        ':integration:httpurlconnection-auto',
        ':integration:okhttp3-auto',
        ':integration:okhttp3-manual',
        ':integration:anr',
        ':integration:crash',
        ':integration:slowrendering',
        ':integration:sessionreplay',
        ':integration:interactions',
        ':integration:navigation',
        ':integration:lifecycle',
        ':integration:customtracking',
        ':integration:networkmonitor',
        ':integration:webview',
        ':integration:applicationlifecycle'

// Test App
include ':app'

// Main entry point
include ':agent'