-keep class com.splunk.rum.integration.agent.api.SplunkRUMAgent
-keep class com.splunk.rum.integration.agent.api.SplunkRUMAgent$Companion
-keep class com.splunk.rum.integration.agent.api.AgentConfiguration
-keep class com.splunk.rum.integration.agent.api.extension.ViewExtKt
