---
name: Bug Report
title: "[BUG] Short descriptive title of the issue"
labels: bug
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        ### Mandatory Fields

  - type: textarea
    id: issue-description
    attributes:
      label: 1. Describe the Issue
      description: A clear and concise description of what the bug is. What were you trying to achieve, and what went wrong?
      placeholder: Describe the issue here...
    validations:
      required: true

  - type: dropdown
    id: client-version
    attributes:
      label: 2. Agent Version
      description: Please select the exact version of the `splunk-otel-android` agent you are using.
      options:
        - 0.1.0
        - 0.2.0
        - 0.3.0
        - 0.4.0
        - 0.5.0
        - 0.6.0
        - 0.7.0
        - 0.8.0
        - 0.9.0
        - 0.10.0
        - 0.11.0
        - 0.12.0
        - 0.13.0
        - 0.14.0
        - 0.15.0
        - 0.17.0
        - 1.0.0-rc.1
        - 1.0.0-rc.2
        - 1.0.0-rc.3
        - 1.0.0
        - 1.1.0
        - 1.2.0
        - 1.3.0
        - 1.3.1
        - 1.4.0
        - 1.5.0
        - 1.6.0
        - 1.7.0
        - 1.8.0
        - 1.8.1
        - 1.9.0
        - 1.10.0
        - 2.0.0
        - 2.0.2
        - Other (please specify in "Additional Context")
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Optional Fields

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 3. Steps to Reproduce (Scenario)
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: Provide detailed steps to reproduce the issue...
    validations:
      required: false

  - type: input
    id: affected-devices
    attributes:
      label: 4. Affected Devices / Android Versions
      description: |
        Please specify the device(s) and Android version(s) where you observed the issue.
        Example:
        - Device: Google Pixel 6, Android Version: 13 (API 33)
        - Device: Samsung Galaxy S22, Android Version: 12 (API 31)
      placeholder: e.g., Google Pixel 6 (Android 13), Samsung Galaxy S22 (Android 12)
    validations:
      required: false

  - type: textarea
    id: logs-stack-trace
    attributes:
      label: 5. Relevant Logs / Stack Trace
      description: If applicable, include any relevant logcat output, stack traces, or crash reports. Please format them using code blocks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: code-snippet
    attributes:
      label: 6. Code Snippet / Minimal Reproducible Example
      description: If possible, provide a small code snippet or a link to a minimal reproducible example that demonstrates the issue. This helps in quickly understanding and debugging the problem.
      render: java
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 7. Additional Context
      description: Add any other context about the problem here. For example, if it only happens under specific network conditions, or after a certain period of time.
      placeholder: Any other relevant information...
    validations:
      required: false
---
