blank_issues_enabled: false
contact_links:
  - name: Splunk RUM for Android — Installation & Configuration
    url: https://help.splunk.com/en/splunk-observability-cloud/manage-data/instrument-front-end-applications/instrument-mobile-and-web-applications-for-splunk-rum/instrument-android-applications-for-splunk-rum/splunk-rum-android-agent-version-2.0.0-and-above/install-the-splunk-rum-android-agent
    about: Setup, configuration, and usage documentation for the Agent.
  - name: Splunk RUM for Android — Troubleshooting
    url: https://help.splunk.com/en/splunk-observability-cloud/manage-data/instrument-front-end-applications/instrument-mobile-and-web-applications-for-splunk-rum/instrument-android-applications-for-splunk-rum/splunk-rum-android-agent-version-2.0.0-and-above/troubleshoot-android-instrumentation
    about: Common issues and how to resolve them before filing a bug.