-keep interface com.splunk.sdk.common.storage.IAgentStorage
-keep class com.splunk.sdk.common.storage.AgentStorage
-keep class com.splunk.sdk.common.storage.AgentStorage$Companion
-repackageclasses 'com.splunk.sdk.common.storage'