name: Gradle wrapper validation

on:
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
  push:
    paths:
      - '**/gradle/wrapper/**'

jobs:
  validation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: gradle/actions/wrapper-validation@da187c8e6ffbd3802e00f2477aa5a822b25f2dda # v4.4.4
