name: Gradle wrapper validation

on:
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
  push:
    paths:
      - '**/gradle/wrapper/**'

jobs:
  validation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: gradle/actions/wrapper-validation@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
