name: "Continuous Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build and test
        run: touch ./local.properties; ./gradlew build javadoc assemble
