name: PR build

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Build and test
        run: touch ./local.properties; ./gradlew build javadoc --no-daemon
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          lycheeVersion: 0.10.3
