name: PR build

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: ./.github/actions/validate-pr-title
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build and test
        run: touch ./local.properties; ./gradlew check javadoc assemble
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.0.7
  check_codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 17
      - name: Run ktlint
        run: ./gradlew ktlintCheck
        
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          fail: true
          lycheeVersion: v0.19.1