name: PR build

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 17

      - name: Build and test
        run: touch ./local.properties; ./gradlew check javadoc assemble
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.0.7
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          lycheeVersion: v0.16.1
