name: PR build

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR
        uses: actions/checkout@v4.2.2
      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Validating PR title: \"$PR_TITLE\""

          REGEX='^\[?(WIP|wip)?\]?\s*(DEMRUM-[0-9]+(,\s?DEMRUM-[0-9]+)*|NO-TICKET):\s.+$'

          if [[ "$PR_TITLE" =~ $REGEX ]]; then
            echo "✅ PR title is valid."
          else
            echo "❌ PR title is invalid."
            echo "It must match the format: DEMRUM-1234: Description"
            echo "Or: DEMRUM-1234, DEMRUM-5678: Description"
            echo "Or: NO-TICKET: Description"
            exit 1
          fi
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build and test
        run: touch ./local.properties; ./gradlew check javadoc assemble
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.0.7
  check_codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 17
      - name: Run ktlint
        run: ./gradlew ktlintCheck
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          lycheeVersion: v0.16.1
