name: PR build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Build and test
        run: echo rum.beacon.url=http://backend > ./local.properties; echo rum.auth.token=abc123 >> ./local.properties; ./gradlew build --no-daemon
