name: PR build

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v3.10.0
        with:
          distribution: adopt
          java-version: 11

      - name: Build and test
        run: touch ./local.properties; ./gradlew build javadoc --no-daemon
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          fail: true
          lycheeVersion: 0.10.3
